---
language: python
cache: pip

os: linux
dist: bionic

git:
  depth: false
  quiet: true

env:
  global:
    - ROLE_NAME: docker
  jobs:
    - MOLECULE_DISTRO: ubuntu/20.04
    - MOLECULE_DISTRO: ubuntu/18.04
    - MOLECULE_DISTRO: debian/10
    - MOLECULE_DISTRO: debian/9
    - MOLECULE_DISTRO: fedora/32
    - MOLECULE_DISTRO: fedora/31
    - MOLECULE_DISTRO: centos/8
    - MOLECULE_DISTRO: centos/7

before_install:
  # Initialize LXD
  - sudo chmod ugo+rw /var/lib/lxd/unix.socket
  - lxd init --auto

install: pip install ansible ansible-lint yamllint molecule git+https://github.com/bonddim/molecule-lxd

before_script:
  # Get latest yamllint config
  - curl -sSo .yamllint https://raw.githubusercontent.com/ansible/galaxy/master/galaxy/importer/linters/yamllint.yaml
  # Use actual Ansible Galaxy role name
  - mv ../ansible-role-${ROLE_NAME} ../bonddim.${ROLE_NAME}
  - cd ../bonddim.${ROLE_NAME}

script: molecule test

notifications:
  webhooks:
    urls: https://galaxy.ansible.com/api/v1/notifications/
    if: (tag IS present) OR (branch = main)
    on_failure: never
