---
- name: Check current docker-compose version
  command: docker-compose --version
  register: compose_current_version
  changed_when: false
  failed_when: false

- when: docker_compose_version == "latest"
  block:
    - name: Check latest docker-compose version
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        method: GET
        headers:
          Accept: application/vnd.github.v3+json
      register: compose_latest_version

    - name: Set docker-compose version number
      set_fact:
        docker_compose_version: "{{ compose_latest_version.json.tag_name }}"

- name: Install docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "{{ docker_compose_install_path }}"
    force: "{{ (docker_compose_version not in compose_current_version.stdout | default('')) | ternary(true, false) }}"
    mode: 0755
